<a href="https://colab.research.google.com/github/Tanmai1808/Jupyter_notebook/blob/main/Lab_assignment1_PSDV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
%config InlineBackend.figure_format = 'retina'


# **Creating Arrays**

#### 1. Create a 1D array with 20 random integers between 1 and 100.
**Hint:** Use the `np.random.randint()` function, specifying the range and size.
#### 2. Create a 5x5 matrix where all the border elements are 1, and the inside elements are 0.
#### 3. Create a diagonal matrix with values `[1, 2, 3, 4]` on the diagonal.
#### 4. Create an array of shape (3, 3) where each row contains numbers from 1 to 3.
**Hint:** Use `np.tile()` to repeat arrays along rows or columns.
#### 5. Create a 1D array with alternating 0s and 1s of length 10.
#### 6. Create a 3x3 matrix with random integers between 10 and 20, and set the datatype to `int32`.

In [ ]:
import numpy as np

# Create a 1D array with 20 random integers between 1 and 100
array = np.random.randint(1, 101, size=20)

print(array)


[70 60 89 80 75 49 90 35 78 35 41  9 66 60 18 39 43 71 67 47]


In [ ]:
import numpy as np

# Create a 5x5 matrix with all elements initialized to 0
matrix = np.zeros((5, 5), dtype=int)

# Set the border elements to 1
matrix[0, :] = 1  # Top row
matrix[-1, :] = 1  # Bottom row
matrix[:, 0] = 1  # Left column
matrix[:, -1] = 1  # Right column

print(matrix)


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
diagonal_values = [1, 2, 3, 4]

# Create the diagonal matrix
matrix = np.diag(diagonal_values)

print(matrix)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [ ]:
arr = np.tile([1, 2, 3], (3, 1))

print(arr)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
arr = np.tile([0, 1], 5)

print(arr)

[0 1 0 1 0 1 0 1 0 1]


In [2]:
import numpy as np
matrix = np.random.randint(10, 21, size=(3, 3), dtype=np.int32)

print(matrix)


[[12 12 14]
 [15 20 13]
 [20 11 19]]


# **Array Attributes**

####1. Create a NumPy array of shape (4, 5) filled with random integers between 1 and 10. Now use an appropriate attribute of an array and find the following:

  1. shape of the array
  2. size of the array
  3. number of dimensions
  4. data type

####2. Write a Python function that takes an array as input and returns the number of dimensions (ndim) of the array.
Test the function with the following arrays:

  1. A 1D array with 5 elements.
  2. A 2D array of size (3x4).
  3. A 3D array of size (2x3x4).


####3. Create a NumPy array with the elements between 1 to 100 and use the dtype attribute to find out the data type of the elements. Modify the program to create arrays with elements of type float and string, and observe the changes in dtype.

####4. Write a Python function that:
  1. Creates a 6×3 array of integers using NumPy.
  2. Prints the shape of the array using the shape attribute.
  3. Reshapes the array to 3×6 and prints the new shape.



####5. Write a program to:
  1. Create an array of any size with all elements being 0 and use the appropriate attribute to print the size (in bytes) of each element in the array.
  2. Create an array of any size with elements between 1 to 10 and print the size.
  3. Create another array with floating-point numbers of any size and observe how the size changes.



In [3]:
arr = np.random.randint(1, 11, size=(4, 5))

# Find the attributes
shape = arr.shape
size = arr.size
ndim = arr.ndim
dtype = arr.dtype

# Output the results
print("Array:\n", arr)
print("Shape:", shape)
print("Size:", size)
print("Number of Dimensions:", ndim)
print("Data Type:", dtype)

Array:
 [[8 1 9 6 3]
 [4 5 4 2 8]
 [8 9 8 4 3]
 [8 6 1 7 7]]
Shape: (4, 5)
Size: 20
Number of Dimensions: 2
Data Type: int64


In [4]:
def array_dimensions(arr):
    return arr.ndim

# Test the function with different arrays

# 1D array with 5 elements
array_1d = np.array([1, 2, 3, 4, 5])

# 2D array of size (3x4)
array_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# 3D array of size (2x3x4)
array_3d = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
                     [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]])

# Testing the function
print("Dimensions of array_1d:", array_dimensions(array_1d))  # Expected: 1
print("Dimensions of array_2d:", array_dimensions(array_2d))  # Expected: 2
print("Dimensions of array_3d:", array_dimensions(array_3d))

Dimensions of array_1d: 1
Dimensions of array_2d: 2
Dimensions of array_3d: 3


In [5]:
arr_int = np.arange(1, 101)

# Create an array with float elements between 1 and 100
arr_float = np.arange(1, 101, dtype=float)

# Create an array with string elements
arr_string = np.array([str(i) for i in range(1, 101)])

# Output the dtype for each array
print("Array of integers:")
print("Data type:", arr_int.dtype)

print("\nArray of floats:")
print("Data type:", arr_float.dtype)

print("\nArray of strings:")
print("Data type:", arr_string.dtype)

Array of integers:
Data type: int64

Array of floats:
Data type: float64

Array of strings:
Data type: <U3


In [6]:
def reshape_array():
    # Create a 6x3 array of integers
    array = np.arange(18).reshape(6, 3)  # 18 integers, reshaped into 6x3
    print("Original array shape:", array.shape)

    # Reshape the array to 3x6
    reshaped_array = array.reshape(3, 6)
    print("Reshaped array shape:", reshaped_array.shape)

# Call the function
reshape_array()

Original array shape: (6, 3)
Reshaped array shape: (3, 6)


In [7]:
def array_size_examples():
    # Create an array of size 5x5 with all elements being 0
    zero_array = np.zeros((5, 5))
    print("Array with all elements 0 (5x5):")
    print(zero_array)
    print(f"Size of each element in zero_array (in bytes): {zero_array.itemsize}")

    # Create an array of size 5x5 with elements between 1 and 10
    random_array = np.random.randint(1, 11, size=(5, 5))
    print("\nArray with elements between 1 and 10 (5x5):")
    print(random_array)
    print(f"Size of each element in random_array (in bytes): {random_array.itemsize}")

    # Create an array of size 5x5 with floating-point numbers
    float_array = np.random.rand(5, 5)  # Generates random floats between 0 and 1
    print("\nArray with floating-point numbers (5x5):")
    print(float_array)
    print(f"Size of each element in float_array (in bytes): {float_array.itemsize}")

# Call the function
array_size_examples()

Array with all elements 0 (5x5):
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Size of each element in zero_array (in bytes): 8

Array with elements between 1 and 10 (5x5):
[[ 3  3  6  7  3]
 [10  8  9  1  5]
 [ 8  4  4  4  3]
 [ 7  6  8  5  9]
 [10  2  9  7  3]]
Size of each element in random_array (in bytes): 8

Array with floating-point numbers (5x5):
[[0.09641287 0.03439861 0.10000487 0.83018496 0.00546493]
 [0.09464013 0.44644557 0.39876466 0.68601714 0.17090758]
 [0.44348694 0.45401187 0.14208725 0.56790495 0.28942409]
 [0.01209092 0.01630787 0.55955751 0.97490318 0.56665209]
 [0.43256417 0.0081989  0.83344426 0.22037943 0.01389383]]
Size of each element in float_array (in bytes): 8


# **Sorting and Partioning**

####1. Given an array arr, sort the array in ascending order without modifying the original array. Print both the original and sorted arrays.(use np.sort())

####2. You have arr = np.array([50, 30, 40, 20]) and names = np.array(["A", cc"B", "C", "D"]).
Sort the arr values in ascending order and rearrange the names array accordingly.(use np.argsort() to get sorted indices and reorder names)

####3. Write code to find the k smallest elements from the array arr. Print these elements in ascending order.(use np.partition())

####4. Partition the array arr such that all elements smaller than a particular number(user input) appear before those greater than or equal to that number. Print the partitioned array.(use np.partition() to find the pivot value's index)

####5. Sort each row of a 2D array arr in ascending order.(use np.sort() with axis parameter)

####6. Print k largest elements of an array arr in descending order.(use np.partition() to find top k elements)

####7. Given an array arr(containing possible negative values), sort the array in ascending order based on the absolute values of the elements. Print the sorted array.(use np.argsort() with a custom key for absolute values)

####8. Given an array arr, sort only the elements greater than k in ascending order, keeping the other elements in their original positions.(create a mask to find elements greater than k, use np.sort() to sort them then reassign the sorted values back to their original indices in the array)

In [8]:
def sort_array():
    # Create a sample array
    arr = np.array([5, 2, 9, 1, 5, 6])

    # Sort the array using np.sort(), which returns a sorted copy
    sorted_arr = np.sort(arr)

    # Print the original and sorted arrays
    print("Original array:", arr)
    print("Sorted array:", sorted_arr)

# Call the function
sort_array()

Original array: [5 2 9 1 5 6]
Sorted array: [1 2 5 5 6 9]


In [9]:
def sort_and_rearrange():
    # Define the arrays
    arr = np.array([50, 30, 40, 20])
    names = np.array(["A", "B", "C", "D"])

    # Get the indices that would sort the array arr
    sorted_indices = np.argsort(arr)

    # Use the sorted indices to rearrange both arr and names
    sorted_arr = arr[sorted_indices]
    sorted_names = names[sorted_indices]

    # Print the sorted arrays
    print("Original arr:", arr)
    print("Original names:", names)
    print("Sorted arr:", sorted_arr)
    print("Rearranged names:", sorted_names)

# Call the function
sort_and_rearrange()

Original arr: [50 30 40 20]
Original names: ['A' 'B' 'C' 'D']
Sorted arr: [20 30 40 50]
Rearranged names: ['D' 'B' 'C' 'A']


In [10]:
def k_smallest_elements(arr, k):
    # Use np.partition to find the k smallest elements
    partitioned_arr = np.partition(arr, k)

    # The first k elements in the partitioned array are the k smallest elements
    smallest_elements = partitioned_arr[:k]

    # Sort the smallest elements to print them in ascending order
    sorted_smallest_elements = np.sort(smallest_elements)

    # Print the result
    print(f"The {k} smallest elements in ascending order:", sorted_smallest_elements)

# Example usage
arr = np.array([50, 30, 40, 20, 10, 70, 60])
k = 3
k_smallest_elements(arr, k)

The 3 smallest elements in ascending order: [10 20 30]


In [12]:
import numpy as np

# Function to partition the array
def partition_array(arr, num):
    # Using np.partition to get the partitioned array
    partitioned_arr = np.partition(arr, np.searchsorted(arr, num))
    return partitioned_arr

# Example usage
arr = np.array([10, 20, 5, 15, 25, 30, 2])
pivot = 15  # User input can replace this
partitioned_arr = partition_array(arr, pivot)

print("Original array:", arr)
print("Partitioned array:", partitioned_arr)


Original array: [10 20  5 15 25 30  2]
Partitioned array: [ 2  5 20 15 25 30 10]


In [13]:
def sort_rows(arr):
    # Sort each row of the 2D array in ascending order
    sorted_arr = np.sort(arr, axis=1)

    # Print the sorted 2D array
    print("Array with each row sorted in ascending order:")
    print(sorted_arr)

# Example usage
arr = np.array([[50, 30, 40, 20],
                [10, 70, 60, 90],
                [80, 10, 20, 30]])

sort_rows(arr)

Array with each row sorted in ascending order:
[[20 30 40 50]
 [10 60 70 90]
 [10 20 30 80]]


In [14]:
def k_largest_elements(arr, k):
    # Use np.partition to partition the array, with the k largest elements in the last k positions
    partitioned_arr = np.partition(arr, -k)

    # Extract the top k elements and sort them in descending order
    largest_elements = partitioned_arr[-k:]
    sorted_largest_elements = np.sort(largest_elements)[::-1]  # Sort in descending order

    # Print the result
    print(f"The {k} largest elements in descending order:", sorted_largest_elements)

# Example usage
arr = np.array([50, 30, 40, 20, 10, 70, 60])
k = 3
k_largest_elements(arr, k)

The 3 largest elements in descending order: [70 60 50]


In [15]:
def sort_by_absolute_values(arr):
    # Use np.argsort with a custom key for absolute values
    sorted_indices = np.argsort(np.abs(arr))

    # Use the sorted indices to rearrange the array
    sorted_arr = arr[sorted_indices]

    # Print the sorted array
    print("Array sorted by absolute values:", sorted_arr)

# Example usage
arr = np.array([50, -30, 40, -20, 10, -70, 60])
sort_by_absolute_values(arr)

Array sorted by absolute values: [ 10 -20 -30  40  50  60 -70]


In [16]:
def sort_elements_greater_than_k(arr, k):
    # Create a mask identifying elements greater than k
    mask = arr > k

    # Extract the elements greater than k
    elements_to_sort = arr[mask]

    # Sort the extracted elements in ascending order
    sorted_elements = np.sort(elements_to_sort)

    # Reassign the sorted elements back to their original indices in the array
    arr[mask] = sorted_elements

    # Print the modified array
    print("Array after sorting elements greater than k:", arr)

# Example usage
arr = np.array([50, 30, 40, 20, 10, 70, 60])
k = 30
sort_elements_greater_than_k(arr, k)

Array after sorting elements greater than k: [40 30 50 20 10 60 70]


# **Indexing and slicing**

#### 1. 2D Array Indexing
Consider the following 2D array:
`arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])`
- Access the element at row index 1 and column index 2.
- Extract the first row.
- Extract the last column.

#### 2. Boolean Indexing
Given an array `arr = np.array([2, 5, 8, 11, 14, 17, 20])`, use boolean indexing to:
- Extract all values greater than 10.
- Replace all values greater than 15 with -1.

#### 3. Fancy Indexing
Using the 2D array `arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])`, write code to:

- Select the elements at positions (0,2), (1,1), and (2,0).
- Use fancy indexing to create a submatrix with rows 0 and 2, and columns 1 and 2.

- **Hint:**
 - For 1st part, use arrays of row and column indices
 - For 2nd part, you can create a submatrix using fancy indexing by using np.newaxis to match the dimensions


#### 4. Slicing 1D array
Given the array `arr = np.array([1, 3, 5, 7, 9, 11, 13, 15])`, write code to:

- Extract the first 4 elements.
- Extract every second element from the entire array.
- Extract elements from index 2 to the end, stepping by 2.

#### 5. Slicing a 2D Array
Given the following 2D array:
`arr_2d = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120]])`
- Slice and print the last two columns of 1st row.
- Slice and print the last row, reversed.

#### 6. Handling Out-of-Range Indices in Slicing vs. Indexing
Given the array:
`arr = np.array([10, 20, 30, 40, 50])`


- What will be the output of the following slicing operations? Explain why they work, even though some indices are out of range.
 - print(arr[2:10])  
 - print(arr[-10:3])    

- Compare the behavior of slicing to accessing a single element with an out-of-range index (e.g., arr[10]). Why does slicing not raise an error in these cases, but indexing does?

#### 7.  Work with an Audio File

Download the audio file from the following link: Simple Logo - Pixabay. Load the audio file using pydub and complete the following tasks:

- Extract the first second of the audio and plot its waveform.
   - Hint: Use the frame rate to calculate how many samples are in 1 second, and use slicing to extract this part.

-   Extract the last second of the audio and plot its waveform.
  

-  Combine the samples from the first second and the last second into a new array and plot the combined waveform.
 - Hint: Use NumPy’s np.concatenate() function to merge the two slices.

In [ ]:
import numpy as np
ar_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])
element_row1_col2= ar_2d[1,2]
first_row=ar_2d[0,:]
last_column=ar_2d[:,-1]
print(element_row1_col2)
print(first_row)
print(last_column)

30
[ 5 10 15]
[15 30 45]


In [17]:
import numpy as np

# Define the array
arr = np.array([2, 5, 8, 11, 14, 17, 20])

# Extract all values greater than 10
values_greater_than_10 = arr[arr > 10]

# Replace all values greater than 15 with -1
arr[arr > 15] = -1

values_greater_than_10, arr

(array([11, 14, 17, 20]), array([ 2,  5,  8, 11, 14, -1, -1]))

In [18]:
# Define the 2D array
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

# Select elements at positions (0,2), (1,1), and (2,0)
selected_elements = arr_2d[[0, 1, 2], [2, 1, 0]]

# Create a submatrix with rows 0 and 2, and columns 1 and 2 using fancy indexing
submatrix = arr_2d[np.array([0, 2])[:, np.newaxis], np.array([1, 2])]

selected_elements, submatrix


(array([15, 25, 35]),
 array([[10, 15],
        [40, 45]]))

In [19]:
import numpy as np

# Define the 1D array
arr = np.array([1, 3, 5, 7, 9, 11, 13, 15])

# Extract the first 4 elements
first_four_elements = arr[:4]

# Extract every second element from the entire array
every_second_element = arr[::2]

# Extract elements from index 2 to the end, stepping by 2
elements_from_index2_step2 = arr[2::2]

first_four_elements, every_second_element, elements_from_index2_step2


(array([1, 3, 5, 7]), array([ 1,  5,  9, 13]), array([ 5,  9, 13]))

In [20]:
import numpy as np

# Define the 2D array
arr_2d = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120]])

# Slice and print the last two columns of the 1st row
last_two_columns_first_row = arr_2d[0, -2:]

# Slice and print the last row, reversed
last_row_reversed = arr_2d[-1, ::-1]

last_two_columns_first_row, last_row_reversed


(array([30, 40]), array([120, 110, 100,  90]))

In [ ]:
[30,40,50] because it simply goes as far as possible up to the end of the array.

[10,20,30] The start index -10 is much smaller than the minimum index, but in slicing, negative indices wrap around to the start of the array. However, since -10 is smaller than the array length, it starts at index 0.

For code arr[10] it gives "INDEX ERROR" because there is no element in this index as it is out of range ( while accessing a single element with out of range, NumPy checks whether the index is valid )

For code arr[7:10], NumPy tries to extract a range of elements. If the stop index is out of range, it stops at the end of the array without raising an error.

# **Reshaping in NumPy**


####1. Create a 2D array of shape (3, 5). Flatten it into a 1D array and then reshape it back into a (5, 3) array.

####2. Create a 1D array
```
arr = np.array([1, 2, 3, 4, 5])
```
####Reshape arr into (5,1), then convert to (5,) and then convert it into (1,5).


####3. Create a 1D NumPy array with values ranging from 1 to 100. Reshape it into a (10, 10) matrix. Apply '.ravel()' and '.flatten()' on the matrix and modify the original matrix. Compare the outputs of both methods and explain the difference in memory sharing.


####4. Generate a 5x5 NumPy matrix representing pixel intensities from an image. Use slicing to extract the central 3x3 section of the matrix and flatten it. How does reshaping impact the spatial relationships of the pixels?


####5. Create a 3-channel RGB image as a NumPy array of shape (3, 4, 4) with random integer values between 0 and 255. Flatten the image using '.reshape()' and reshape it back to its original shape. Explain the order of pixel data stored and how reshaping affects the channel structure.



In [26]:
import numpy as np

# Step 1: Create a 2D array of shape (3, 5)
array_2d = np.array([[1, 2, 3, 4, 5],
                     [6, 7, 8, 9, 10],
                     [11, 12, 13, 14, 15]])

print("Original 2D array (3, 5):")
print(array_2d)

# Step 2: Flatten the 2D array into a 1D array
array_1d = array_2d.flatten()
print("\nFlattened 1D array:")
print(array_1d)

# Step 3: Reshape the 1D array back into a (5, 3) array
array_reshaped = array_1d.reshape((5, 3))
print("\nReshaped array (5, 3):")
print(array_reshaped)


Original 2D array (3, 5):
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

Flattened 1D array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

Reshaped array (5, 3):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [27]:
import numpy as np

# Step 1: Create a 1D array
arr = np.array([1, 2, 3, 4, 5])
print("Original 1D array (5,):")
print(arr)

# Step 2: Reshape into (5, 1)
arr_reshaped_5_1 = arr.reshape((5, 1))
print("\nReshaped array (5, 1):")
print(arr_reshaped_5_1)

# Step 3: Convert back to (5,)
arr_flattened = arr_reshaped_5_1.reshape((5,))
print("\nFlattened back to (5,):")
print(arr_flattened)

# Step 4: Reshape into (1, 5)
arr_reshaped_1_5 = arr_flattened.reshape((1, 5))
print("\nReshaped array (1, 5):")
print(arr_reshaped_1_5)


Original 1D array (5,):
[1 2 3 4 5]

Reshaped array (5, 1):
[[1]
 [2]
 [3]
 [4]
 [5]]

Flattened back to (5,):
[1 2 3 4 5]

Reshaped array (1, 5):
[[1 2 3 4 5]]


In [28]:
import numpy as np

# Step 1: Create a 1D array with values from 1 to 100
arr = np.arange(1, 101)
print("Original 1D array:")
print(arr)

# Step 2: Reshape into a (10, 10) matrix
matrix = arr.reshape((10, 10))
print("\nReshaped (10, 10) matrix:")
print(matrix)

# Step 3: Apply .ravel() and .flatten()
ravel_output = matrix.ravel()
flatten_output = matrix.flatten()

# Step 4: Modify the original matrix
matrix[0, 0] = 999
print("\nModified original matrix:")
print(matrix)

# Step 5: Compare ravel and flatten outputs after modification
print("\nRavel output after modification (shares memory with original matrix):")
print(ravel_output)

print("\nFlatten output after modification (does not share memory with original matrix):")
print(flatten_output)


Original 1D array:
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]

Reshaped (10, 10) matrix:
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]

Modified original matrix:
[[999   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 

In [29]:
import numpy as np

# Step 1: Generate a 5x5 matrix representing pixel intensities
image_matrix = np.array([[10, 20, 30, 40, 50],
                         [60, 70, 80, 90, 100],
                         [110, 120, 130, 140, 150],
                         [160, 170, 180, 190, 200],
                         [210, 220, 230, 240, 250]])

print("Original 5x5 matrix:")
print(image_matrix)

# Step 2: Extract the central 3x3 section
central_section = image_matrix[1:4, 1:4]
print("\nCentral 3x3 section:")
print(central_section)

# Step 3: Flatten the central 3x3 section
flattened_central_section = central_section.flatten()
print("\nFlattened central 3x3 section:")
print(flattened_central_section)


Original 5x5 matrix:
[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]
 [210 220 230 240 250]]

Central 3x3 section:
[[ 70  80  90]
 [120 130 140]
 [170 180 190]]

Flattened central 3x3 section:
[ 70  80  90 120 130 140 170 180 190]


In [30]:
import numpy as np

# Step 1: Create a 3-channel RGB image as a NumPy array of shape (3, 4, 4)
np.random.seed(0)  # For reproducibility
rgb_image = np.random.randint(0, 256, (3, 4, 4), dtype=np.uint8)
print("Original 3-channel RGB image (3, 4, 4):")
print(rgb_image)

# Step 2: Flatten the image using .reshape()
flattened_image = rgb_image.reshape(-1)
print("\nFlattened image:")
print(flattened_image)

# Step 3: Reshape it back to its original shape
reshaped_image = flattened_image.reshape(3, 4, 4)
print("\nReshaped image back to (3, 4, 4):")
print(reshaped_image)


Original 3-channel RGB image (3, 4, 4):
[[[172  10 127 140]
  [ 47 170 196 151]
  [117 166  22 183]
  [192 204  33 216]]

 [[ 67 179  78 154]
  [251  82 162 219]
  [195 118 125 139]
  [103 125 229 216]]

 [[  9 164 116 108]
  [211 222 161 159]
  [ 21  81  89 165]
  [242 214 102  98]]]

Flattened image:
[172  10 127 140  47 170 196 151 117 166  22 183 192 204  33 216  67 179
  78 154 251  82 162 219 195 118 125 139 103 125 229 216   9 164 116 108
 211 222 161 159  21  81  89 165 242 214 102  98]

Reshaped image back to (3, 4, 4):
[[[172  10 127 140]
  [ 47 170 196 151]
  [117 166  22 183]
  [192 204  33 216]]

 [[ 67 179  78 154]
  [251  82 162 219]
  [195 118 125 139]
  [103 125 229 216]]

 [[  9 164 116 108]
  [211 222 161 159]
  [ 21  81  89 165]
  [242 214 102  98]]]


# **Universal Functions**

Q1) Given an array x = [1, 4, 9, 16, 25], compute the square root of each element in the array and print the result.

Q2) Create an array angles =[0, $\frac{\pi}{2}$, $\pi$, $\frac{3\pi}{2}$]
, calculate the sine of each angle and print the result.



Q3) Given two arrays a =[True, False, True] and b = [False, False, True], perform an element-wise logical AND operation and print the result.

Q4) Create two arrays x = [1, 2, 3, 4] and y = [2, 2, 3, 5], perform an element-wise comparison (x < y) and print the result.

Q5) Create an array x =[-2, -1, 0, 1, 2, 3, 4], compute the following element-wise operation:

* If an element is negative, square it.
* If an element is non-negative, compute its exponential.
Print the resulting array.

In [21]:
x=np.array([1,4,9,16,25])
x**(1/2)

array([1., 2., 3., 4., 5.])

In [22]:
import numpy as np

# Define the array of angles
angles = np.array([0, np.pi/2, np.pi, 3*np.pi/2])

# Compute the sine of each angle
sine_values = np.sin(angles)

# Print the result
print(sine_values)

[ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00]


In [23]:
a= np.array([True,False,True])
b= np.array([False, False, True])
c=a&b
print(c)

[False False  True]


In [24]:
x= np.array([1, 2, 3, 4])
y=np.array([2, 2, 3, 5])
z=x < y
z

array([ True, False, False,  True])

In [25]:
import numpy as np

# Given array
x = np.array([-2, -1, 0, 1, 2, 3, 4])

# Compute the operation based on the condition
result = np.where(x < 0, x**2, np.exp(x))

# Print the resulting array
print(result)


[ 4.          1.          1.          2.71828183  7.3890561  20.08553692
 54.59815003]


# **Aggregations**

####1. Generate a random array of size 10.
 calculate the following:
- Print the array
- The sum of all elements.
- The mean of the array.
- The standard deviation.
- Find 5$*$Minimum -3$*$Maximum

####2. Generate a 4x5 matrix with random integers between 1 and 50.
- Print the matrix.
- Compute the mean of all elements in the matrix.
- Compute the sum of each row in the matrix.

####3. Generate a random 3x3 matrix with random integers between 1 to 10
- Find the minimum value in each column and store it in a separate list min.
- Find the maximum value in each row and store it in a separate list max.
- Find the value of minimum of list max - maximum of list min.

####4. Given the array : data = np.array([15, 25, 35, 45, 55, 65]):
- Find the minimum value.
- Subtract this minimum value from all elements of the array and then calculate the mean of the resulting array.

####5. Given the array : arr = np.array([3, 5, 7, 9, 11]):
- Compute the cumulative sum of the elements.
- Compute the cumulative product of the elements.

####6. Imagine you have a dataset representing the scores of 4 students in 3 subjects:
scores = np.array([[85, 92, 78], [88, 76, 95], [91, 89, 82], [75, 85, 88]])
- Compute the average score for each student.
- Compute the highest score in each subject.
- Determine the overall average score for all students across all subjects.

In [ ]:
#Question 1

# Generate a random array of size 10
arr = np.random.rand(10)

# Print the array
print("Array:", arr)

# Calculate the sum of all elements
sum_arr = np.sum(arr)
print("Sum of all elements:", sum_arr)

# Calculate the mean of the array
mean_arr = np.mean(arr)
print("Mean of the array:", mean_arr)

# Calculate the standard deviation
std_arr = np.std(arr)
print("Standard deviation:", std_arr)

# Find 5 * Minimum - 3 * Maximum
result = 5 * np.min(arr) - 3 * np.max(arr)
print("5 * Minimum - 3 * Maximum:", result)


Array: [5.64298007e-01 3.56355975e-01 1.30963909e-01 4.49996683e-01
 3.32693134e-01 6.97352207e-01 6.53351142e-01 5.88215150e-04
 6.42060251e-01 6.73885329e-01]
Sum of all elements: 4.5015448530491105
Mean of the array: 0.45015448530491103
Standard deviation: 0.22997727315331928
5 * Minimum - 3 * Maximum: -2.089115545649599


In [ ]:
#Question 2
# Generate a 4x5 matrix with random integers between 1 and 50
matrix = np.random.randint(1, 51, size=(4, 5))

# Print the matrix
print("Matrix:")
print(matrix)

# Compute the mean of all elements in the matrix
mean_matrix = np.mean(matrix)
print("\nMean of all elements in the matrix:", mean_matrix)

# Compute the sum of each row in the matrix
row_sums = np.sum(matrix, axis=1)
print("\nSum of each row:")
print(row_sums)


Matrix:
[[12 37  4 32 14]
 [ 4 17  8 15 31]
 [37 46  3 23 32]
 [24 23 20 29 20]]

Mean of all elements in the matrix: 21.55

Sum of each row:
[ 99  75 141 116]


In [ ]:
#Question 3
# Generate a 3x3 matrix with random integers between 1 and 10
matrix = np.random.randint(1, 11, size=(3, 3))

# Print the matrix
print("Matrix:")
print(matrix)

# Find the minimum value in each column and store it in a list 'min'
min_values = np.min(matrix, axis=0)
print("\nMinimum value in each column:", min_values)

# Find the maximum value in each row and store it in a list 'max'
max_values = np.max(matrix, axis=1)
print("\nMaximum value in each row:", max_values)

# Compute the minimum of list 'max' - maximum of list 'min'
result = np.min(max_values) - np.max(min_values)
print("\nMinimum of max values - Maximum of min values:", result)


Matrix:
[[4 8 4]
 [1 3 1]
 [4 2 5]]

Minimum value in each column: [1 2 1]

Maximum value in each row: [8 3 5]

Minimum of max values - Maximum of min values: 1


In [ ]:
#Question 4
data = np.array([15, 25, 35, 45, 55, 65])

# Find the minimum value
min_value = np.min(data)
print(min_value)

# Subtract the minimum value from all elements
resulting_array = data - min_value

# Calculate the mean of the resulting array
mean_result = np.mean(resulting_array)

print(mean_result)


15
25.0


In [ ]:
#Question 5
arr = np.array([3, 5, 7, 9, 11])

# Compute the cumulative sum of the elements
cumulative_sum = np.cumsum(arr)

# Compute the cumulative product of the elements
cumulative_product = np.cumprod(arr)

print("Cumulative sum:", cumulative_sum)
print("Cumulative product:", cumulative_product)


Cumulative sum: [ 3  8 15 24 35]
Cumulative product: [    3    15   105   945 10395]


In [ ]:
#Question 6
scores = np.array([[85, 92, 78], [88, 76, 95], [91, 89, 82], [75, 85, 88]])

# Compute the average score for each student (mean across columns)
average_score_per_student = np.mean(scores, axis=1)

# Compute the highest score in each subject (maximum across rows)
highest_score_per_subject = np.max(scores, axis=0)

# Compute the overall average score for all students across all subjects
overall_average_score = np.mean(scores)

print("Average score for each student:", average_score_per_student)
print("Highest score in each subject:", highest_score_per_subject)
print("Overall average score for all students:", overall_average_score)


Average score for each student: [85.         86.33333333 87.33333333 82.66666667]
Highest score in each subject: [91 92 95]
Overall average score for all students: 85.33333333333333


# **Broadcasting in NumPy**

---





####1. Given two arrays:

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) (shape: (3, 3))
B = np.array([10, 20, 30]) (shape: (3,))
Perform elementwise addition of A and B using broadcasting and print the result.

What is the resulting shape?





####2. Write a function check_broadcasting(shape1, shape2) that:

Accepts two shapes as input and checks if they are broadcast-compatible.
Use the function to test the following shape pairs:
(3, 4) and (4,)
(2, 1, 5) and (3, 5)
(2, 3) and (2,)

For each case:

* State whether broadcasting is possible.

* If possible, state the resulting shape of the operation

####3. Create a 2D array A of shape (3, 5) with random integers between 1 and 10.
Create a 1D array B of shape (5,) with random integers between 1 and 5.
Use broadcasting to subtract B from each row of A and print the result.

####4.  Create a 3D array A with shape (2, 4, 3) filled with random integers between 0 and 10.

* Create an array B of shape (4, 3) containing a constant value of 5.
* Use broadcasting to add B to each 2D array slice of A.
* Print the result

####5. : You are given a grayscale image of shape (32, 32), where each pixel value is an integer. You want to apply a scaling factor of 0.5 to all the pixel values using broadcasting.


* Use broadcasting to scale the image by multiplying it with the scaling factor 0.5.
* Verify that the pixel values of the image are halved by printing the scaled image.

####6. Calculate the distance between an observation point and a set of code points (codes). The goal is to find the closest code to the observation by calculating the Euclidean distance between each code and the observation.

* Given two arrays :

codes = np.array([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0],
    [7.0, 8.0, 9.0],
    [1.0, 1.0, 1.0],
    [2.0, 3.0, 4.0]
])


observation = np.array([3.0, 3.0, 3.0])


* Use broadcasting to calculate the squared Euclidean distance between the observation and each code.
* Find and print the index of the closest code to the observation.
* Print the distance between the observation and the closest code.

**HINT : use np.argmin() to find the index of the closest code**




In [ ]:
#Question 1
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([10, 20, 30])

# Perform elementwise addition using broadcasting
result = A + B

print("Resulting array:")
print(result)

# Print the shape of the resulting array
print("Shape of the resulting array:", result.shape)


Resulting array:
[[11 22 33]
 [14 25 36]
 [17 28 39]]
Shape of the resulting array: (3, 3)


In [ ]:
#Question 2

def check_broadcasting(shape1, shape2):
    try:
        # Try to apply broadcasting using numpy
        result = np.broadcast(np.empty(shape1), np.empty(shape2))
        # If broadcasting is possible, return the resulting shape
        return True, result.shape
    except ValueError:
        # If broadcasting is not possible, return False
        return False, None

# Test cases
test_cases = [
    ((3, 4), (4,)),
    ((2, 1, 5), (3, 5)),
    ((2, 3), (2,))
]

# Checking each test case
for shape1, shape2 in test_cases:
    can_broadcast, result_shape = check_broadcasting(shape1, shape2)
    if can_broadcast:
        print(f"Broadcasting is possible between {shape1} and {shape2}. Resulting shape: {result_shape}")
    else:
        print(f"Broadcasting is not possible between {shape1} and {shape2}.")


Broadcasting is possible between (3, 4) and (4,). Resulting shape: (3, 4)
Broadcasting is possible between (2, 1, 5) and (3, 5). Resulting shape: (2, 3, 5)
Broadcasting is not possible between (2, 3) and (2,).


In [ ]:
#Question 3

# Create a 2D array A with shape (3, 5) and random integers between 1 and 10
A = np.random.randint(1, 11, size=(3, 5))

# Create a 1D array B with shape (5,) and random integers between 1 and 5
B = np.random.randint(1, 6, size=5)

# Subtract B from each row of A using broadcasting
result = A - B

# Print the results
print("Array A:")
print(A)
print("\nArray B:")
print(B)
print("\nResult of A - B (using broadcasting):")
print(result)


Array A:
[[ 1  1  1  8  2]
 [ 3  5 10 10  1]
 [ 1  7  5  4  8]]

Array B:
[5 1 4 3 3]

Result of A - B (using broadcasting):
[[-4  0 -3  5 -1]
 [-2  4  6  7 -2]
 [-4  6  1  1  5]]


In [ ]:
#Question 4

# Create a 3D array A with shape (2, 4, 3) filled with random integers between 0 and 10
A = np.random.randint(0, 11, size=(2, 4, 3))

# Create a 2D array B with shape (4, 3) containing constant values of 5
B = np.full((4, 3), 5)

# Add B to each 2D slice of A using broadcasting
result = A + B

# Print the results
print("Array A (3D):")
print(A)
print("\nArray B (2D):")
print(B)
print("\nResult of A + B (using broadcasting):")
print(result)


Array A (3D):
[[[ 2  2  8]
  [ 6  3  7]
  [ 0  7 10]
  [ 8  6  9]]

 [[ 4  2  5]
  [ 6  4  4]
  [ 5  6  7]
  [ 8  0  2]]]

Array B (2D):
[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]

Result of A + B (using broadcasting):
[[[ 7  7 13]
  [11  8 12]
  [ 5 12 15]
  [13 11 14]]

 [[ 9  7 10]
  [11  9  9]
  [10 11 12]
  [13  5  7]]]


In [ ]:
#Question 5

# Create a grayscale image of shape (32, 32) with random integer values between 0 and 255 (representing pixel values)
image = np.random.randint(0, 256, size=(32, 32), dtype=int)

# Define the scaling factor
scaling_factor = 0.5

# Apply the scaling factor using broadcasting
scaled_image = image * scaling_factor

# Print the original and scaled images
print("Original Image:")
print(image)

print("\nScaled Image (after applying a scaling factor of 0.5):")
print(scaled_image)


Original Image:
[[153 199  81 ... 212 230   3]
 [219  15 104 ...  21 190 170]
 [ 33  79  77 ... 123  13 141]
 ...
 [ 70 154 214 ...  55 209  66]
 [180 100  78 ... 171  69 138]
 [164 186 233 ... 151  44  34]]

Scaled Image (after applying a scaling factor of 0.5):
[[ 76.5  99.5  40.5 ... 106.  115.    1.5]
 [109.5   7.5  52.  ...  10.5  95.   85. ]
 [ 16.5  39.5  38.5 ...  61.5   6.5  70.5]
 ...
 [ 35.   77.  107.  ...  27.5 104.5  33. ]
 [ 90.   50.   39.  ...  85.5  34.5  69. ]
 [ 82.   93.  116.5 ...  75.5  22.   17. ]]


In [ ]:
#Question 6

# Given code points and observation
codes = np.array([[1.0, 2.0, 3.0],
                  [4.0, 5.0, 6.0],
                  [7.0, 8.0, 9.0],
                  [1.0, 1.0, 1.0],
                  [2.0, 3.0, 4.0]])

observation = np.array([3.0, 3.0, 3.0])

# Calculate the squared Euclidean distance using broadcasting
distances_squared = np.sum((codes - observation) ** 2, axis=1)

# Find the index of the closest code point
closest_index = np.argmin(distances_squared)

# Calculate the Euclidean distance (take the square root of the squared distance)
closest_distance = np.sqrt(distances_squared[closest_index])

# Print the index of the closest code and the corresponding distance
print(f"Index of the closest code: {closest_index}")
print(f"Distance between the observation and the closest code: {closest_distance}")


Index of the closest code: 4
Distance between the observation and the closest code: 1.4142135623730951


# Concatenation

1. Write a program to vertically stack arrays using `np.vstack` and print the result: (Use any three 1D arrays) <br/>
<br/>
2. Write a program to horizontally stack arrays using `np.hstack`. Print the result: (Use any three 1D arrays) <br/>
<br/>
3. Given two 2D arrays of the same row size, horizontally stack them using `np.hstack` and print the result:<br/>
`m = np.array([[2, 4], [3, 6]])`<br/>
`n = np.array([[4, 8], [5, 10]])`<br/>
<br/>
4. Using `np.vstack`, stack the following arrays vertically and print the results:<br/>
`a = np.array([11, 12, 13])`<br/>
`b = np.array([[14, 15, 16], [17, 18, 19]])`<br/>
<br/>
5. Concatenate the following 2D arrays along different axes using `np.concatenate`. Demonstrate how to concatenate them along axis 0 and axis 1.<br/>
`x = np.array([[1, 2], [3, 4]])`<br/>
`y = np.array([[5, 6], [7, 8]])`<br/>
`z = np.array([[9, 10], [11, 12]])`<br/>

In [ ]:
#Question 1

# Create three 1D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])

# Vertically stack the arrays
stacked_arr = np.vstack((arr1, arr2, arr3))

# Print the result
print("Vertically Stacked Array:")
print(stacked_arr)


In [ ]:
#Question 2

# Create three 1D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])

# Horizontally stack the arrays
stacked_arr = np.hstack((arr1, arr2, arr3))

# Print the result
print("Horizontally Stacked Array:")
print(stacked_arr)


Horizontally Stacked Array:
[1 2 3 4 5 6 7 8 9]


In [ ]:
#Question 3

# Create the two 2D arrays
m = np.array([[2, 4], [3, 6]])
n = np.array([[4, 8], [5, 10]])

# Horizontally stack the arrays
stacked_arr = np.hstack((m, n))

# Print the result
print("Horizontally Stacked Array:")
print(stacked_arr)


Horizontally Stacked Array:
[[ 2  4  4  8]
 [ 3  6  5 10]]


In [ ]:
#Question 4

# Create the arrays
a = np.array([11, 12, 13])
b = np.array([[14, 15, 16], [17, 18, 19]])

# Vertically stack the arrays
stacked_arr = np.vstack((a, b))

# Print the result
print("Vertically Stacked Array:")
print(stacked_arr)


In [ ]:
#Question 5

# Create the 2D arrays
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
z = np.array([[9, 10], [11, 12]])

# Concatenate along axis 0 (vertically)
concatenated_axis0 = np.concatenate((x, y, z), axis=0)

# Concatenate along axis 1 (horizontally)
concatenated_axis1 = np.concatenate((x, y, z), axis=1)

# Print the results
print("Concatenated along axis 0 (vertically):")
print(concatenated_axis0)
print("\nConcatenated along axis 1 (horizontally):")
print(concatenated_axis1)


Concatenated along axis 0 (vertically):
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]

Concatenated along axis 1 (horizontally):
[[ 1  2  5  6  9 10]
 [ 3  4  7  8 11 12]]


# Boolean Masking

1. Use Boolean masking to filter elements from a 1D array:
Write a program to create a 1D array and use Boolean masking to filter out all elements greater than 5.<br/>

2. Apply a Boolean mask to a 2D array:
Given the 2D array below, create a Boolean mask to select all elements greater than 10 and print the masked elements.<br/>
`arr = np.array([[5, 12, 18], [7, 1, 3], [11, 6, 14]])`
 <br/>
3. Create a Boolean mask using a condition on an array:
Create a 1D array of integers from 0 to 10. Use a Boolean mask to filter out all even numbers and print the result.<br/>
Example:
`arr = np.arange(11)`
<br/>
4. Combine Boolean masks using logical operations:
Given the array below, create and combine two Boolean masks:<br/>
One mask selects elements greater than 5.
The other mask selects elements divisible by 3.
Combine the masks using logical AND and print the result.
Example:
`arr = np.array([1, 3, 6, 9, 12, 15])`
<br/>
5. Mask elements in a 2D array and replace them:
Write a program to replace all elements less than 5 in the 2D array below with 0 using Boolean masking.
<br/>
6.  Count elements satisfying a condition using Boolean masks:
Write a program to count how many elements in the array below are greater than 5.
<br/>

In [ ]:
#Question 1
# Create a 1D array
arr = np.array([1, 3, 6, 8, 2, 4, 7, 5])

# Use Boolean masking to filter out elements greater than 5
filtered_arr = arr[arr <= 5]

# Print the filtered array
print("Original Array:", arr)
print("Filtered Array (elements <= 5):", filtered_arr)


Original Array: [1 3 6 8 2 4 7 5]
Filtered Array (elements <= 5): [1 3 2 4 5]


In [ ]:
#Question 2
# Create a 2D array
arr = np.array([[5, 12, 18], [7, 1, 3], [11, 6, 14]])

# Create a Boolean mask for elements greater than 10
mask = arr > 10

# Apply the mask to the array
masked_elements = arr[mask]

# Print the masked elements
print("Masked Elements (greater than 10):", masked_elements)


Masked Elements (greater than 10): [12 18 11 14]


In [ ]:
#Question 3

# Create a 1D array of integers from 0 to 10
arr = np.arange(11)

# Create a Boolean mask for odd numbers (i.e., numbers that are not even)
mask = arr % 2 != 0

# Apply the mask to the array
filtered_arr = arr[mask]

# Print the filtered result
print("Array with only odd numbers:", filtered_arr)


Array with only odd numbers: [1 3 5 7 9]


In [ ]:
#Question 4

# Create the array
arr = np.array([1, 3, 6, 9, 12, 15])

# Create the first mask for elements greater than 5
mask_1 = arr > 5

# Create the second mask for elements divisible by 3
mask_2 = arr % 3 == 0

# Combine the masks using logical AND
combined_mask = mask_1 & mask_2

# Apply the combined mask to the array
filtered_arr = arr[combined_mask]

# Print the filtered result
print("Elements greater than 5 and divisible by 3:", filtered_arr)


Elements greater than 5 and divisible by 3: [ 6  9 12 15]


In [ ]:
#Question 5

# Create a 2D array
arr = np.array([[1, 6, 3], [8, 2, 9], [4, 7, 5]])

# Create a Boolean mask for elements less than 5
mask = arr < 5

# Replace elements less than 5 with 0 using the mask
arr[mask] = 0

# Print the modified array
print("Modified Array:")
print(arr)


Modified Array:
[[0 6 0]
 [8 0 9]
 [0 7 5]]


In [ ]:
#Question 6

# Create the array
arr = np.array([1, 3, 6, 9, 12, 15])

# Create a Boolean mask for elements greater than 5
mask = arr > 5

# Count how many elements satisfy the condition (greater than 5)
count = np.sum(mask)

# Print the count
print("Number of elements greater than 5:", count)


Number of elements greater than 5: 4
